In [1]:
from complexFuncs import DSM_colapse2,complexity,DSM_rearrange,DSM_idx_arrange
import numpy as np

This is the dsm from Sinha & de Weck. Pump controller system

In [2]:
Demo_dsm = np.array([  [5  ,0  ,1.5,0  ,0.5],
                       [0  ,2  ,0.5,0  ,1.5],
                       [2.5,1.5,1  ,.5 ,0],
                       [0  ,  0,1.5,1  ,0],
                       [1.5,.5 ,0  ,0  ,3]])

Calculate the complexity of the system:
complexity returns a dictionary with the complexity breakdown 'C', 'C1', 'C2', 'C3' , 'C2*C3' and 'SVD' 

In [3]:
complexity(Demo_dsm)

{'C': 25.4300767292727,
 'C1': 12.0,
 'C2': 12.0,
 'C3': 1.119173060772725,
 'C2*C3': 13.4300767292727,
 'SVD': (array([[ 6.57192300e-01,  1.11022302e-16,  2.55955135e-01,
          -5.08453565e-02, -7.07106781e-01],
         [ 6.57192300e-01,  4.16333634e-17,  2.55955135e-01,
          -5.08453565e-02,  7.07106781e-01],
         [ 1.38090135e-16, -7.88205438e-01,  1.19908323e-01,
           6.03617579e-01,  3.31400081e-17],
         [ 3.69048184e-01,  2.25694245e-17, -9.11597730e-01,
           1.81088422e-01, -1.50022116e-17],
         [-8.39544701e-17, -6.15412209e-01, -1.53575751e-01,
          -7.73099154e-01,  8.86511593e-17]]),
  array([2.13577921e+00, 2.13577921e+00, 6.62153447e-01, 6.62153447e-01,
         1.03092850e-16]),
  array([[ 8.72521884e-17,  1.31045574e-17,  7.88205438e-01,
           6.55227872e-18,  6.15412209e-01],
         [-6.57192300e-01, -6.57192300e-01,  4.82033076e-17,
          -3.69048184e-01,  5.08107476e-17],
         [-5.08453565e-02, -5.08453565e-02, -

use DSM_rearrange to rearrange the columns and rows so the system is still the same. This will swap column 0 with column 1. This should be congruent columns

In [4]:
rearraged_demo_dsm = DSM_rearrange(Demo_dsm,[0,1])
rearraged_demo_dsm

array([[2. , 0. , 0.5, 0. , 1.5],
       [0. , 5. , 1.5, 0. , 0.5],
       [1.5, 2.5, 1. , 0.5, 0. ],
       [0. , 0. , 1.5, 1. , 0. ],
       [0.5, 1.5, 0. , 0. , 3. ]])

Use DSM_idx_arrange to arrange the original dsm to a new index. This can be any index

In [5]:
indexed_demo_dsm = DSM_rearrange(Demo_dsm,[0,1,3,2,4])
indexed_demo_dsm

array([[3. , 0. , 1.5, 0. , 0.5],
       [0. , 1. , 2.5, 0.5, 1.5],
       [0.5, 1.5, 5. , 0. , 0. ],
       [0. , 1.5, 0. , 1. , 0. ],
       [1.5, 0.5, 0. , 0. , 2. ]])

Use DSM_colapse2 to increase the abstraction level, but to keep complexity of the system

In [6]:
colapsed_demo_dsm = DSM_colapse2(Demo_dsm,[[1,2],[3,4]])
colapsed_demo_dsm

array([[ 3.        ,  1.40031001,  0.45390062],
       [ 0.46677   , 10.        ,  1.69493754],
       [ 1.36170185,  1.69493754,  3.        ]])

Calculate the complexity of the new dsm to check with the demo DSM we started with

In [7]:
complexity(colapsed_demo_dsm)

{'C': 25.430076729272706,
 'C1': 16.0,
 'C2': 7.072557546954531,
 'C3': 1.3333333333333333,
 'C2*C3': 9.430076729272708,
 'SVD': (array([[-5.77350269e-01, -1.11022302e-16,  8.16496581e-01],
         [-5.77350269e-01, -7.07106781e-01, -4.08248290e-01],
         [-5.77350269e-01,  7.07106781e-01, -4.08248290e-01]]),
  array([2., 1., 1.]),
  array([[-0.57735027, -0.57735027, -0.57735027],
         [-0.        ,  0.70710678, -0.70710678],
         [-0.81649658,  0.40824829,  0.40824829]]))}

In [8]:
abs(complexity(colapsed_demo_dsm)['C']-complexity(Demo_dsm)['C'])<np.finfo(np.float32).eps

True

In [3]:
x=[1,2,3,3]

In [4]:
x[0:]

[1, 2, 3, 3]

In [10]:
import numpy as np

In [12]:
sum(np.array(x)==max(x))

2

In [18]:
x.count(3)

2

In [17]:
print(x)

[3, 3, 2, 1]
